<a href="https://colab.research.google.com/github/doremon11/Goeduhub-GO_STP_4414-/blob/main/task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment/Task 3
Reg No.:-GO_STP_4414
Name: Kala Sri Sowmya

1.Import the numpy package under the name np and Print the numpy version and the configuration

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


2.Create a null vector of size 10

In [2]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3.Create Simple 1-D array and check type and check data types in array

In [3]:
import numpy as np
a = np.array([1, 2, 3])   
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


4.How to find number of dimensions, bytes per element and bytes of memory used?

In [4]:
import numpy as np
  
# create a numpy 1d-array
x = np.array([100,20,34])
  
print("Size of the array: ",x.size)
  
print("Memory size of one array element in bytes: ",x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",x.size * x.itemsize)

Size of the array:  3
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24


5.Create a null vector of size 10 but the fifth value which is 1

In [5]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6.Create a vector with values ranging from 10 to 49

In [6]:
import numpy as np
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


7.Reverse a vector (first element becomes last)

In [7]:
import numpy as np
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


8.Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9.Find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
import numpy as np
nums = np.array([1,2,0,0,4,0])
print("Original array:")
print(nums)
print("Indices of elements equal to zero of the said array:")
result = np.where(nums == 0)[0]
print(result)

Original array:
[1 2 0 0 4 0]
Indices of elements equal to zero of the said array:
[2 3 5]


10.Create a 3x3 identity matrix

In [10]:
import numpy as np
array_2D=np.eye(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11.Create a 3x3x3 array with random values

In [11]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.94548495 0.77600955 0.57059364]
  [0.37821438 0.7582331  0.4059736 ]
  [0.7082082  0.45674228 0.00734892]]

 [[0.03863536 0.08578408 0.19620155]
  [0.7555747  0.88440341 0.88367068]
  [0.21294775 0.43740443 0.74243812]]

 [[0.94504855 0.34985722 0.05966971]
  [0.01376126 0.47243881 0.25128077]
  [0.06295462 0.83311252 0.21007679]]]


12.Create a 10x10 array with random values and find the minimum and maximum values

In [12]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.97909243 0.61397461 0.48225362 0.20850194 0.88172475 0.42593896
  0.13944725 0.49581887 0.43014518 0.15941719]
 [0.02866964 0.26946551 0.95832757 0.25925851 0.14492259 0.02644575
  0.9672438  0.14699309 0.22491074 0.95952393]
 [0.26865257 0.68040301 0.36782829 0.66649032 0.73527097 0.52662595
  0.36569645 0.02330158 0.23289277 0.6934448 ]
 [0.43985045 0.8601855  0.65978419 0.423025   0.21252998 0.52563267
  0.67512909 0.13837456 0.16022034 0.98017825]
 [0.46229118 0.41803193 0.46739488 0.41748706 0.75477563 0.4763877
  0.9918702  0.26647446 0.41251662 0.78896948]
 [0.42969822 0.99251823 0.50033047 0.14218845 0.6424704  0.90357085
  0.00452984 0.45281833 0.35133258 0.04199669]
 [0.57859219 0.20147734 0.23948908 0.23633795 0.11203907 0.99759944
  0.98466533 0.24103773 0.87067332 0.52781147]
 [0.85450354 0.59739632 0.41985342 0.9202624  0.86874834 0.44687159
  0.77863821 0.8697603  0.36961219 0.64914861]
 [0.48426366 0.70634393 0.67869858 0.86378533 0.15733227 0.580089

13.Create a random vector of size 30 and find the mean value

In [14]:
import numpy as np
x = np.random.random(30)
print(x)
print(np.mean(x))

[0.04538248 0.79249928 0.91096201 0.75483415 0.35292042 0.53142885
 0.7109579  0.93663291 0.36919438 0.11687471 0.4000869  0.94969026
 0.0398631  0.25782903 0.80495642 0.67245125 0.42841765 0.41765232
 0.77228848 0.45233654 0.26087652 0.65588261 0.51407918 0.83889138
 0.48405774 0.85772444 0.3400001  0.74781516 0.38388245 0.28698091]
0.5362483184986157


14.Create a 2d array with 1 on the border and 0 inside

In [13]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


15.How to add a border (filled with 0's) around an existing array?

In [15]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example - [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [16]:
import numpy as np
Arr= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(Arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
print(Arr[:,2])

[ 3 10]


17.How to Convert a 1D array to a 2D array with 2 rows

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = arr.reshape(2, 3)

print(newarr)

[[1 2 3]
 [4 5 6]]


18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])

Desired Output:

 array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
import numpy as np
a=np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


19.Write a program to show how Numpy taking less memory compared to Python List?

In [20]:
import numpy as np
  
# importing system module
import sys
  
# declaring a list of 1000 elements 
S= range(1000)
  
# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(S))
  
# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
  
# declaring a Numpy array of 1000 elements 
D= np.arange(1000)
  
# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)
  
# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


20.Write a program to show how Numpy taking less time compared to Python List?

In [21]:
import numpy
import time
   
# size of arrays and lists
size = 1000000  
   
# declaring lists
list1 = range(size)
list2 = range(size)
   
# declaring arrays
array1 = numpy.arange(size)  
array2 = numpy.arange(size)
   
# capturing time before the multiplication of Python lists
initialTime = time.time()
  
# multiplying  elements of both the lists and stored in another list
resultantList = [(a * b) for a, b in zip(list1, list2)]
   
# calculating execution time
print("Time taken by Lists to perform multiplication:", 
      (time.time() - initialTime),
      "seconds")
   
# capturing time before the multiplication of Numpy arrays
initialTime = time.time()
  
# multiplying  elements of both the Numpy arrays and stored in another Numpy array 
resultantArray = array1 * array2
   
# calculating execution time 
print("Time taken by NumPy Arrays to perform multiplication:",
      (time.time() - initialTime),
      "seconds")

Time taken by Lists to perform multiplication: 0.16809558868408203 seconds
Time taken by NumPy Arrays to perform multiplication: 0.0036094188690185547 seconds
